#!/usr/bin/env zsh
# shellcheck shell=bash
# Copyright (c) 2016-2020 Dyne.org Foundation
# live-sdk is written and maintained by Ivan J. <parazyd@dyne.org>
#
# This file is part of live-sdk
#
# This source code is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this source code. If not, see <http://www.gnu.org/licenses/>.

arch="amd64"

export PATH="$PATH:/usr/sbin:/sbin"

# Comment if you wish to disable stage4 archives for faster rebuilding
CPIO_STAGE4=1

# extra_packages for all images
extra_packages+=(
	live-config
	live-config-sysvinit
	syslinux
	syslinux-common
	isolinux
	rsync
	squashfs-tools
	xorriso
	cryptsetup
	firmware-linux
)

case "$arch" in
i386)  extra_packages+=(linux-image-686) ;;
amd64) extra_packages+=(linux-image-amd64) ;;
esac
