#!/usr/bin/env zsh
## configuration file for devuan-desktop-live blend -- Beowulf release


base_packages+=(
	lsof
	bash-completion
	texinfo
	acpi-support-base
	acpi-fakekey
	aptitude
	apt-listchanges
	debootstrap
	discover
	dnsutils
	doc-debian
	docutils-common
	docutils-doc
	ftp
	gettext
	gnupg2
	gparted
	grub-pc-bin
	$grubversion
	iw
	laptop-detect
	lvm2
	mdadm
	mlocate
	mutt
	ncurses-term
	net-tools
	netcat-traditional
	nfs-common
	procmail
	reportbug
	telnet
	traceroute
	usbutils
	util-linux-locales
	w3m
	whois
)


extra_packages+=(

	task-desktop
	task-laptop
	task-xfce-desktop
	fontsnaps
	task-print-server
	popularity-contest
	refractainstaller-base
	refractasnapshot-base
	yad
	refractainstaller-gui
	refractasnapshot-gui
	libgtk3-perl    #need to add this for graphical debconf
	gvfs-backends

)


extra_packages+=(
	firmware-atheros
	firmware-bnx2
	firmware-bnx2x
	firmware-brcm80211
	firmware-intelwimax
	firmware-iwlwifi
	firmware-libertas
#	firmware-linux-nonfree
#	firmware-misc-nonfree
	firmware-myricom
	firmware-netxen
	firmware-qlogic
	firmware-ralink
	firmware-realtek
	firmware-ti-connectivity
	firmware-zd1211
)


purge_packages=(
	devuan-baseconf
	debian-keyring
	elinks
	elinks-data
	git
	git-core
	git-man
	liberror-perl
	libfsplib0
	libtre5
	openntpd
	openssh-server
	openssh-sftp-server
	tmux
	zsh
	zsh-common
	intel-microcode
	iucode-tool
	amd64-microcode
)



custom_deb_packages+=(


)
