#!/usr/bin/env zsh
## configuration file for devuan-desktop-live blend

vars+=(username userpass default_shell mkefi grubversion hookscripts)
arrs+=(custom_deb_packages)

blend_name="devuan-desktop-live_"

release="beowulf"
version="3.0.0"

username="devuan"
userpass="devuan"
default_shell="/bin/bash"

# comment to disable:
#hookscripts="yes"

# uncomment to create uefi-bootable iso
mkefi="yes"
efi_work="$BLENDPATH/${release}/efi-files"

#grubversion="grub-pc"
grubversion="grub-efi-amd64"

# Uncomment for amd64
base_packages+=(grub-efi-amd64-bin grub-efi-ia32-bin)

mirror="http://pkgmaster.devuan.org/merged"
section="main contrib non-free"


#base_packages_option=(--no-install-recommends)
#extra_packages_option=(--no-install-recommends)


release_conf="$BLENDPATH/${release}/config"


### package sets are defined in the corresponding $release/config file

source $release_conf

## image_name depends on release and version

image_name="${os}_${release}_${version}_${arch}_desktop"


